name: Node.js CI/CD Pipeline

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checking out the repository
      uses: actions/checkout@v2

    - name: Setting up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '18.17.0' 

    - name: Installing dependencies
      run: npm install

    - name: Building the application
      run: npm run build

    - name: Deploying to Digital Ocean
      if: github.ref == 'refs/heads/main' && github.event_name == 'push'
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.HOST }}
        username: root
        key: ${{ secrets.SSH_KEY }}
        passphrase: ${{ secrets.PASS }}
        script: |
          export NVM_DIR="$HOME/.nvm"
          [ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"  
          [ -s "$NVM_DIR/bash_completion" ] && \. "$NVM_DIR/bash_completion"  

          nvm use 18.17.0

          cd Nextjs/
          git pull origin main
          npm install
          npm run build
          npm run dev